$(function(){function l(k){var g=f[k],p,q=g.funcs;if(!g.running){g.running=!0;for(p=0;p<q.length;p++){if("number"==typeof q[p]){g.funcs=q.slice(p+1);g.timeout=setTimeout(function(){g.running=!1;l(k)},q[p]);return}try{q[p]()}catch(c){throw g.funcs=[],g.running=!1,c;}}g.funcs=[];g.running=!1}}var f={};($.delay=function(k,g){1==arguments.length&&(g=k,k=" ");var p=f[k];p||(p=f[k]={running:!1,funcs:[],timeout:!1});$.isArray(g)?Array.prototype.push.apply(p.funcs,g):p.funcs.push(g);l(k);return this}).clear=
function(k){null==k&&(k=" ");if(k=f[k])clearTimeout(k.timeout),k.funcs=[],k.running=!1}});
(function(l){var f=[],k={},g=Object.prototype.toString,p=Array.isArray||function(a){return"[object Array]"===g.call(a)},q=function(a,d){try{if(null!=d&&null!=a){d+="";a+="";var b;for(b=f.length-1;0<=b;b--)if(f[b].valid_from(a,d))return f[b].to_internal(a,d)}}catch(e){}},c=function(a,d){try{if(null!=d&&null!=a){a+="";var b;for(b=f.length-1;0<=b;b--)if(f[b].valid_to(a,d))return f[b].from_internal(a,d)}}catch(e){}},a=l.Base=function(a,d,b){var e,s,t;e=p(b);var n=p(a),m=p(d),h=e?b.length:n?a.length:m?
d.length:void 0;if(!e&&!n&&!m)return c(d,q(a,b+""));if(e&&n&&m)throw"Max two of the three parameters may be an array.";t=[];if(e||n){s=[];if(e&&n)for(e=0;e<h;e++)s[e]=q(a[e],b[e]);else if(e)for(e=0;e<h;e++)s[e]=q(a,b[e]);else for(e=0;e<h;e++)s[e]=q(a[e],b);if(m)for(e=0;e<h;e++)t[e]=c(d[e],s[e]);else for(e=0;e<h;e++)t[e]=c(d,s[e])}else for(s=q(a,b),e=0;e<h;e++)t[e]=c(d[e],s);return t};a.to=function(r,d){return c(r,null!=d&&a.Number?a.Number(d):d)};a.from=function(a,d){return q(a,d)};a.valid=function(a,
d){var b=f.length-1;a+="";if(null==d)for(;0<=b;b--){if(f[b].valid_base(a))return!0}else for(d+="";0<=b;b--)if(f[b].valid_from(a,d))return!0;return!1};a.get_name=function(a){var d;a:{d=a+"";var b;for(b=f.length-1;0<=b;b--)if(f[b].get_name&&f[b].valid_base(d)){d=f[b];break a}d=void 0}if(d)return d.get_name(a)};a.suggest=function(a,d){var b,e,s;e=new RegExp(a.replace(/[\-\[\]{}()*+?.,\\\^$|#\s]/g,"\\$&"),"i");var t=[],n;for(b=f.length-1;0<=b;b--)f[b].suggest_base&&t.push(f[b].suggest_base(a,e));s=t.length;
if(d)for(b in n={match:[],proposed:[],good:[],other:[]},n){for(e=0;e<s;e++)t[e][b]&&n[b].push(t[e][b]);n[b]=[].concat.apply([],n[b])}else{n=[];for(b in{match:!0,proposed:!0,good:!0,other:!0})for(e=0;e<s;e++)t[e][b]&&n.push(t[e][b]);n=[].concat.apply([],n)}return n};a.extend=function(a){if(k[a.name])throw"There is already an extension '"+a.name+"'.";f.push(a);k[a.name]=a};a.extensions=k;a.option=function(a,d){1<arguments.length&&(a={})}})(this);
(function(l){function f(a){return a instanceof g?a.value:"number"===typeof a?a:(new g(a)).value}function k(){throw"Can't modify immutable number.";}var g=l.Base.Number=function(a){if(!(this instanceof g))return new g(a);a=a instanceof g?a.value:"number"===typeof a?a:null==a?0:/\-?(\d+|\d*.\d+)([eE][\-+]?\d+)?/.test(a)?+a:!1;if(!1===a)throw"Can't create a Base.Number with the value '"+a+"'.";this.value=a},p=Array.prototype.slice,q=[{methods:["add","mul"],static_method:function(a){return function(c){c=
new g(c);return c[a].apply(c,p.call(arguments,1))}}},{methods:["sub","div","mod","pow"],static_method:function(a){return function(c,d){return(new g(c))[a](d)}}},{methods:["neg","abs","floor"],static_method:function(a){return function(c){return(new g(c))[a]()}}}],c;for(l=0;l<q.length;l++)for(c=0;c<q[l].methods.length;c++)g[q[l].methods[c]]=q[l].static_method(q[l].methods[c]);g.prototype={value:0,toString:function(){return this.value+""},valueOf:function(){return this.value},add:function(){var a,c=
arguments,d=this.value;for(a=c.length-1;0<=a;a--)d+=f(c[a]);this.value=d;return this},sub:function(a){this.value-=f(a);return this},mul:function(){var a,c=arguments,d=this.value;for(a=c.length-1;0<=a;a--)d*=f(c[a]);this.value=d;return this},div:function(a){a=f(a);if(0===a)throw"division by zero";this.value/=a;return this},mod:function(a){a=f(a);if(0===a)throw"dividend can't be zero";if(0>this.value||0>a)throw"operators in mod can't be negative";this.value%=a;return this},pow:function(a){a=f(a);this.value=
Math.pow(this.value,a);return this},abs:function(){0>this.value&&(this.value=-this.value);return this},neg:function(){this.value=-this.value;return this},floor:function(){this.value=Math.floor(this.value);return this},cmp:function(a){return this.value-f(a)},equals:function(a){return!(this!==a&&f(a)!==this.value)},is_int:function(){return 0===this.value%1},clone:function(){return new g(this.value)},make_immutable:function(){var a,c;for(a=q.length-1;0<=a;a--)for(c=q[a].methods.length-1;0<=c;c--)this[q[a].methods[c]]=
k;return this}};g.ZERO=(new g).make_immutable()})(this);
(function(l){function f(a){var b="["+"0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ".substr(0,a)+"]*";return r[a]=new RegExp("^\\-?"+b+"\\.?"+b+"$","i")}function k(a){return b[a]?"#name# (base #base#)".replace("#name#",b[a]).replace("#base#",a):"base #base#".replace("#base#",a)}function g(b,d){if(d.equals(a))return{digits:[0],neg:!1,pt:!1};d=d.clone();var n,m,h=[],e=0>d.cmp(0);m=c.floor(d.abs());for(var f=d.mod(1),g=0,r=Math.floor(53*Math.log(2)/Math.log(b));0<m.cmp(a);g++)n=c.mod(m,b).valueOf(),h.unshift(n),
m.sub(n).div(b);for(m=h.length;g<r&&!f.equals(a);g++)f.mul(b),n=c.floor(f),f.sub(n),h.push(n.valueOf());if(g>=r)if(g>m)if(h.pop()>=b/2){for(n=h.length;++h[--n]===b;)h[n]=0;h.length=Math.max(n+1,m)}else{for(n=h.length;0===h[--n]&&n>=m;);h.length=n+1}else{if(h[r]>=b/2)for(n=r-1;++h[--n]===b;)h[n]=0;for(n=r;n<h.length;n++)h[n]=0}h[-1]!==p&&(h.unshift(1),m++);0===m&&(h.unshift(0),m++);return{digits:h,neg:e,pt:m===h.length?!1:m}}var p,q="0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ".split(""),c=l.Number,a=c.ZERO,
r=[],d=/^\-?(\d+(\:\d+)*)?\.?(\d+(\:\d+)*)?$/,b={2:"binary",8:"octal",10:"decimal",12:"duodecimal",16:"hexadecimal"},e={proposed:["2","8","10","12","16"],good:["20","36","60","100"],other:"11 13 14 15 18 30 40 50 70 80 90".split(" ")};l.extend({name:"standard",valid_base:function(a){return 2<=a&&36>=a&&parseInt(a,10)+""===a},valid_from:function(a,b){return""!==b&&"."!==b&&"-."!==b&&"-"!==b&&2<=a&&36>=a&&parseInt(a,10)+""===a&&(r[a]?r[a]:f(a)).test(b)},valid_to:function(a,b){return 2<=a&&36>=a&&parseInt(a,
10)+""===a},fractional:!0,to_internal:function(a,b){a=+a;"string"!==typeof b&&(b+="");b=b.toUpperCase().split(".");var d,m,h="-"!==b[0].charAt(0),e=c();m=h?b[0]:b[0].substr(1);var f=b[1];for(d=0;d<m.length;d++)e.mul(a).add("0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ".indexOf(m.charAt(d)));if(f){m=c();for(d=0;d<f.length;d++)m.mul(a).add("0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ".indexOf(f.charAt(d)));m.mul(c.pow(a,-f.length));e.add(m)}return h?e:e.neg()},from_internal:function(a,b){var d,m,h=g(+a,b),e=h.digits,
c=h.pt;d=0;for(m=e.length;d<m;d++)e[d]=q[e[d]];return(h.neg?"-":"")+(c?e.slice(0,c).join("")+"."+e.slice(c).join(""):e.join(""))},get_name:k,suggest_base:function(a,d){var n,m,h,c,f={proposed:[]},g={};if(c=/(\d+)/.exec(a))for(n in c=c[1],1<c&&(f.match=[[c,k(c)]],g[c]=!0),e)for(h=e[n],m=0;m<h.length;m++)-1===h[m].indexOf(c)||g[h[m]]||(f[n]||(f[n]=[]),f[n].push([h[m],k(h[m])]),g[h[m]]=!0);for(n in b)h="#name# (base #base#)".replace("#name#",b[n]).replace("#base#",n),!g[n]&&d.test(h)&&(f.proposed.push([n,
h]),g[n]=!0);return f},options:{uppercase:!0}});l.extend({name:"standard_big",valid_base:function(a){return 36<a&&parseInt(a,10)+""===a},valid_from:function(a,b){if(""!==b&&"."!==b&&"-."!==b&&"-"!==b&&36<a&&parseInt(a,10)+""===a&&d.test(b)){b=b.split(/[\-\.\:]/);a=parseInt(a,10);for(var n=b.length-1;0<=n;n--)if(b[n]>=a)return!1;return!0}return!1},valid_to:function(a,b){return 36<a&&parseInt(a,10)+""===a},fractional:!0,to_internal:function(a,b){a=+a;b=b.split(".");var d,m,h="-"!==b[0].charAt(0),e=
c();m=h?b[0]:b[0].substr(1);var f=b[1]?b[1].split(":"):!1;m=m?m.split(":"):[];for(d=0;d<m.length;d++)e.mul(a).add(m[d]);if(f){m=c();for(d=0;d<f.length;d++)m.mul(a).add(f[d]);m.mul(c.pow(a,-f.length));e.add(m)}return h?e:e.neg()},from_internal:function(a,b){var d=g(+a,b),m=d.digits,c=d.pt;return(d.neg?"-":"")+(c?m.slice(0,c).join(":")+"."+m.slice(c).join(":"):m.join(":"))},get_name:k,options:{}})})(Base);
(function(l){var f=l.Number,k=""==="aa".replace("a","","g")?function(a,b,c){return a.replace(b,c,"g")}:function(a,b,c){for(;a!==(a=a.replace(b,c)););return a},g=function(a){var b,c=arguments;for(b=1;b<c.length;b++)a=k(a,"$"+b,c[b]);return a},p={M:1E3,CM:900,D:500,CD:400,C:100,XC:90,L:50,XL:40,X:10,IX:9,V:5,IV:4,I:1},q={M:3,C:4,X:4,I:4},c={M:6,D:5,C:5,CM:4,CD:4,LM:3,LD:3,L:3,X:3,XM:2,XD:2,XC:2,XL:2,VM:1,VD:1,VC:1,VL:1,V:1,I:1,IM:0,ID:0,IC:0,IL:0,IX:0,IV:0},a={D:3,CD:3,L:2,XL:2,V:1,IV:1},r={M:1E3,IM:999,
VM:995,XM:990,LM:950,CM:900,D:500,ID:499,VD:495,XD:490,LD:450,CD:400,C:100,IC:99,VC:95,XC:90,L:50,IL:49,VL:45,XL:40,X:10,IX:9,V:5,IV:4,I:1};l.extend({name:"roman",fractional:!1,valid_base:function(a){return"roman"===a},valid_from:function(a,b){var c="roman"===a&&/^[IVXLCDM]+$/i.test(b);if(c)try{l.extensions.roman.to_internal("roman",b)}catch(f){c=!1}return c},valid_to:function(a,b){return"roman"===a&&b.is_int()&&0<b.cmp(0)&&0>b.cmp(4E3)},to_internal:function(d,b){b=b.toUpperCase();var e=0,k,t=b.length,
n=this.options.strict?p:r,m,h,w,l,x=1001,v=7,y=4,u;for(k=0;k<t;k++){m=b.charAt(k);h=b.charAt(k+1);k+1<t&&n[m+h]&&(m+=h,k++);h=n[m];w=c[m];l=a[m];x===h?u++:u=1;if(x<h||v<w)throw g(this.options.strict?"Found unexpected sorting order: '$1' followed by '$2' (using strict sorting order).":"Found unexpected sorting order: '$1' followed by '$2' (using non-strict sorting order)",void 0,m);if(v===w){if(!q[m])throw g(this.options.strict?"Found unexpected sorting order: '$1' followed by '$2' (using strict sorting order).":
"Found unexpected sorting order: '$1' followed by '$2' (using non-strict sorting order)",void 0,m);if(x===h&&u>q[m])throw g("Found unexpected repetition: '$1' $2 times in a row",m,u);}else if(void 0!==l&&y===l)throw g(this.options.strict?"Found unexpected sorting order: '$1' followed by '$2' (using strict sorting order).":"Found unexpected sorting order: '$1' followed by '$2' (using non-strict sorting order)",void 0,m);e+=h;x=h;v=w;y=l}return f(e)},from_internal:function(a,b){b=b.valueOf();var c,
f="";for(c in p)for(;b>=p[c];)b-=p[c],f+=c;return this.options.uppercase?f:f.toLowerCase()},get_name:function(a){return"roman numerals"},suggest_base:function(a,b){return/^rom/i.test(a)?{match:[["roman","roman numerals"]]}:b.test("roman numerals")?{proposed:[["roman","roman numerals"]]}:{}},options:{uppercase:!0,strict:!0}})})(Base);
(function(l){l.extend({name:"leet",valid_base:function(f){return"10"===f||"100"===f},valid_from:function(f,k){return k.toLowerCase()===("10"===f?"leet":"100"===f?"le:et":!1)},valid_to:function(f,k){return("10"===f||"100"===f)&&k.equals(1337)},fractional:!1,to_internal:function(f,k){return l.Number(1337)},from_internal:function(f,k){return"10"===f?"leet":"le:et"},options:{}})})(Base);
(function(l,f){function k(a,b){for(var d={},c=0;c<a.length;c++)d[a[c]]=b[c];return d}function g(a,b){var d,c=Array.prototype.slice.call(arguments,1);for(d=0;d<e.length;d++)e[d][a]&&e[d][a].apply(e[d],c)}function p(a,b){var d,c=Array.prototype.slice.call(arguments,2);for(d=0;d<e.length;d++)e[d][a]&&e[d]!==b&&e[d][a].apply(e[d],c)}function q(a){var d,c={},h=!1;for(d in a)b.rows[d].number!==a[d]&&(b.rows[d].number=a[d],c[d]=a[d],h=!0);h&&g("number_change",c)}function c(a,d,c){var h,e,f;if(b.suggestions[0]!==
a||b.suggestions[1]!==d){b.suggestions[0]=a;b.suggestions[1]=d;c=c(d);h=c.match||[];for(e in{proposed:!0,good:!0,other:!0})if(c[e])for(f=0;f<c[e].length;f++)b.bases[c[e][f][0]]||h.push(c[e][f]);g("base_suggest",a,d,h)}}function a(a){var d=b.invalid_number_row;a!==d&&(b.invalid_number_row=a,g("invalid_number_row_change",a,d))}function r(){if(b.suggestions[0]!==d||""!==b.suggestions[1])b.suggestions=[d,""],g("hide_base_suggest")}var d,b={length:0,id_counter:0,origin:d,nu:d,ids:[],bases:{},rows:{},suggestions:[d,
""],invalid_number_row:d},e=[],s=l.Model={_data:b,number_change:function(c,e){if(b.rows[c].number!==e)if(""===e||f.valid(b.rows[c].base,e)){var m=[],h,r=b.rows[c].index;for(h=0;h<b.length;h++)h!==r?m.push(b.rows[b.ids[h]].base):m.push(d);m=f(b.rows[c].base,m,e);m[r]=e;r=""===e?d:c;b.origin!==r&&(h=b.origin,h!==d&&b.rows[h]&&(b.rows[h].is_origin=!1),r!==d&&(b.rows[r].is_origin=!0),b.origin=r,g("origin_change",r,h));a(d);q(k(b.ids,m))}else b.rows[c].number=e,a(c)},base_suggest:function(a,b){c(a,b,function(){return f.suggest(b,
!0)})},hide_base_suggest:r,base_change:function(a,c){if(b.rows[a].is_new){r();var e=++b.id_counter,h=b.length++;b.rows[e]={index:h,base:"",number:"",is_origin:!1,is_new:!1};b.ids[h]=e;b.bases[""]=!0;g("row_add",e);h={};h[a]=c;var l,p,s={},v=!1;for(l in h)p=b.rows[l],p.bases!==h[l]&&(delete b.bases[p.base],b.bases[h[l]]=!0,p.base=h[l],p.name=f.get_name(h[l]),s[l]=h[l],v=!0);v&&g("base_change",s);b.nu!==e&&(l=b.nu,l!==d&&b.rows[l]&&(b.rows[l].is_new=!1),b.rows[e].is_new=!0,b.nu=e,g("new_change",e,l));
b.origin!==d&&(e=b.rows[b.origin],q(k([a],[f(e.base,c,e.number)])))}},delete_row:function(a){var c,e=b.rows,f=b.ids,r=b.bases;for(c=e[a].index;c<b.length-1;c++)f[c]=f[c+1],e[f[c]].index--;f.pop();delete r[e[a].base];delete e[a];b.origin===a&&(b.origin=d);b.nu===a&&(b.nu=d);b.length--;g("row_delete",a)},listen:function(a){e.push(a)},set_state:function(a,c){if("string"===typeof a){var e,h,r,g=0,k=[];e=a.split("|");for(h=0;h<e.length;h++)r=e[h].split("="),f.valid(r[0],r[1])&&(r[1]!==d?k.push({id:g++,
base:r[0],number:r[1],is_origin:!0}):k.push({id:g++,base:r[0]}));k.push({id:g++,is_new:!0});a=k}for(e=0;e<b.length;e++)p("row_delete",c,b.ids[e]);b.length=0;b.ids=[];b.rows={};b.bases={};var l,q,u,z={};for(e=0;e<a.length;e++)l=a[e],l.id!==d?(h=l.id,b.id_counter=Math.max(b.id_counter,h)):h=++b.id_counter,r=l.base===d?"":l.base,g=l.number===d?"":l.number,k=l.name===d?f.get_name(r):l.name,q=l.is_origin===d?!1:l.is_origin,l=l.is_new===d?!1:l.is_new,q&&u===d&&(u=b.origin=h),l&&(b.nu=h),b.ids.push(h),b.rows[h]=
{index:e,base:r,number:g,name:k,is_origin:q,is_new:l},b.bases[r]=!0,l||(z[h]=r),p("row_add",c,h),l&&p("new_change",c,h,d);b.length=a.length;p("base_change",c,z);u!==d&&(g=b.rows[u].number,b.rows[u].number=d,s.number_change(u,g))},get_name:function(a){return b.rows[a].name},get_origin:function(){return b.origin},toString:function(){var a,d=[];for(a=0;a<b.ids.length;a++)b.rows[b.ids[a]].is_origin?d.push(b.rows[b.ids[a]].base+"="+b.rows[b.ids[a]].number):b.rows[b.ids[a]].is_new||d.push(b.rows[b.ids[a]].base);
return d.join("|")}}})(this,Base);
$(function(){function l(a){try{Model.delete_row($(a).parents(".row").attr("id").replace("row_",""))}catch(c){}}function f(a,f){var d;f?(d=$(a),a=d.index()):d=$("li",c).eq(a);d.hasClass("selected")||($(".selected",c).removeClass("selected"),d.addClass("selected"),c.data("selected",a))}function k(a,f){var d,b=c.data("row_id");d=(f?$(a):$("li",c).eq(a)).data("id")+"";return""!==d?(Model.base_change(b,d),$("#number_"+b).focus(),d):!1}var g,p,q=$("#convert"),c=$($.parseHTML('<div id="suggestions" tabindex="2"><ul></ul></div>')).appendTo("#convert");q.on({focus:function(){var a=
$(".focus",q)[0],c=$(this).parents(".row")[0];clearTimeout(g);a!==c&&(a&&$(a).removeClass("focus"),$(c).addClass("focus"))},blur:function(){var a=this;g=setTimeout(function(){$(a).parents(".row").removeClass("focus")},100)}},"input, .remove").on("keydown",".number input",function(a){if((8===a.which||46===a.which)&&""===this.value)return $(this).blur().parents(".row").find(".remove").focus(),!1}).on("blur keypress keyup click change",".number input",function(a){0===$(this).parents(".new").length&&
Model.number_change(this.id.replace("number_",""),this.value)}).on({keydown:function(a){this.autocomplete="off";var g,d;d=a.which;40===d||38===d||34===d||33===d?(a.preventDefault(),g=c.data("selected")+(40===d?1:38===d?-1:34===d?5:-5),d=40===d||38===d,a=$("li",c).length,0>g?g=d?a-1:0:a<=g&&(g=d?0:a-1),f(g)):13===d||9===d&&""!==this.value?(g=c.data("selected"),k(g)&&a.preventDefault()):27===d&&Model.hide_base_suggest()},blur:function(){p=setTimeout(function(){Model.hide_base_suggest()},100)}},".base input").on("focus keypress keyup click change",
".base input",function(a){27===a.which?Model.hide_base_suggest():"keypress"===a.type&&0===a.which||Model.base_suggest(this.id.replace("base_",""),this.value)}).on({focus:function(){$(this).attr("tabindex",1)},blur:function(){$(this).attr("tabindex",2)},click:function(){l(this);return!1},keydown:function(a){if(8===a.which||46===a.which)return l(this),!1}},".remove");c.on("focus",function(){clearTimeout(p);$("#base_"+c.data("row_id")).focus()}).on({mouseover:function(){f(this,!0)},click:function(){k(this,
!0)}},"li")});
$(function(){function l(c){return c.charAt(0).toUpperCase()+c.substr(1)}var f,k=window,g=k.Model,p=[/(\(.+?\))/,"<small>$1</small>"],q=0;$(".row").append('<div class="row_tools"><a href="" title="Remove this row" class="remove" tabindex="2">\u2715</a><span title="Invalid number" class="invalid_number_symbol">!</span></div>');g.set_state("2|8|10|16|36");g.listen({base_change:function(c){JSON.stringify(c);var a,f;for(a in c)(f=g.get_name(a))&&(f=l(f).replace(p[0],p[1])),$("#row_"+a+" .name").html(f),$("#base_"+
a).val(c[a]),"10"===c[a]&&$("#row_"+a).addClass("hilite")},base_suggest:function(c,a,g){var d,b,e=$("#suggestions");q!==f||e.data("row_id")!==c?(f=q,d=$("#base_"+c),b=d.offset(),b.top+=d.innerHeight(),e.data({row_id:c,selected:-1}).show().width(d.width()).offset(b)):e.show();0===g.length&&(g=""===a?[["","No suggestions"]]:[["","No matching bases"]]);a=[];for(c=0;c<g.length;c++)a.push('<li data-id="#id#">#label#</li>'.replace("#id#",g[c][0]).replace("#label#",l(g[c][1])));e.html(a.join(""));$("li",
e).first().trigger("mouseover");a=$(e);d=$(k);g=$(k.document);e=g.scrollTop();c=a.offset();c.top<e?g.scrollTop(c.top-10):(d=d.height(),a=a.height(),e+d<c.top+a&&g.scrollTop(c.top+a-d+10))},hide_base_suggest:function(){$("#suggestions").hide()},number_change:function(c){JSON.stringify(c);var a,f;for(a in c)f=$("#number_"+a),f.val()!==c[a]&&f.val(c[a])},row_delete:function(c){c=$("#row_"+c);var a=$(c.next().find("input:visible")[0]);c.remove();q++;a.focus()},row_add:function(c){$('<div class="row" id="row_#id#"><div class="base"><label class="label" for="number_#id#"><input type="hidden" id="base_#id#" value="" tabindex="1"><strong class="name"></strong></label></div><div class="number"><div class="label"><input id="number_#id#" value="" tabindex="1"></div></div><div class="row_tools"><a href="" title="Remove this row" class="remove" tabindex="2">\u2715</a><span title="Invalid number" class="invalid_number_symbol">!</span></div></div>'.replace(/#id#/g,
c)).appendTo("#convert");q++},new_change:function(c,a){var f;void 0!==a&&(f=$("#row_"+a).removeClass("new"),f.find(".base .label").attr("for","number_"+a),$("#base_"+a).attr("type","hidden").removeAttr("title").prependTo("#row_"+a+" .base"));f=$("#row_"+c).addClass("new");f.find(".base .label").attr("for","base_"+c);f.find(".name").html("Enter a new base here");$("#base_"+c).attr({type:"text",title:"Enter a new base here"});q++},invalid_number_row_change:function(c,a){a&&$("#convert .invalid_number").removeClass("invalid_number");
c&&$("#row_"+c).addClass("invalid_number")}})});
$(function(){function l(a){return $("#convert .base input").filter(function(){return $(this).val()===a}).first()}function f(a){var c=k[Math.floor(Math.random()*k.length)];a.data({base:c[1],number:c[2]}).attr("title",c[2]+" in "+("roman"===c[1]?"roman numerals":"base "+c[1]));$("strong",a).text(c[0]);$("span",a).text(c[2])}var k={fractions:{10:["3.14","1.618","-1.4142"]},"fractional binary":{2:["1100.01101","-0.011101101","100.1","1001.101"]},binary:{2:["101010","101","11111111","-1000","1000011101010"]},
octal:{8:["644"]},hexadecimal:{16:["8BA53"]},duodecimal:{12:["100.A"]},"roman numerals":{roman:["IV","IIII","LXII","XII","MDCCLXXVI",Base("10","roman",(new Date).getFullYear())]},"any base":{13:["42.0009c3"],36:["CON.VERT","333"],85:["45:1.76:15"],100:["4:9","12:95"],1337:["6:1294.126"]}},g,p,q,c=[];for(g in k)for(p in k[g])for(q=0;q<k[g][p].length;q++)c.push([g,p,k[g][p][q]]);k=c;$("#examples a").on("click",function(){var a,c,d=$(this).data("base")+"",b=$(this).data("number")+"",e=l(d),g=!1;f($(this));
e.length||(e=$("#convert .new .base input"),g=!0);c=e.parents(".row").first();a=c.find(".number input").first();$.delay.clear("example");$("#convert .example").removeClass("example");$.delay("example",function(){c.addClass("example")});g&&$.delay("example",[function(){e.focus()},800,function(){var a=1,b=setInterval(function(){a<=d.length?(e.val(d.substr(0,a)).change(),a++):clearInterval(b)},400/d.length)},1E3,function(){$("#suggestions li:first-child").click()},300]);$.delay("example",[function(){a.focus()},
800,function(){var c=1,d=setInterval(function(){c<=b.length?(a.val(b.substr(0,c)).change(),c++):clearInterval(d)},800/b.length)},3E3,function(){c.removeClass("example")}]);return!1}).attr("href","")});
$(function(){function l(a){"change"===(c.event=a.type)?(p.off("change","input"),setTimeout(function(){c.state=q+"";$.post("track?action=use",c)},1E4)):(k.off("mousemove scroll click keydown"),$.post("track?action=human",c),setTimeout(function(){c.state=q+"";$.post("track?action=interested",c)},1E4))}var f=window,k=$(f),g=f.location,p=$("#convert"),q="index"===page_id?f.Model:void 0,c={screen:k.width()+"x"+k.height(),uri:g.pathname+g.search+g.hash,referrer:f.document.referrer,random:Math.floor(4294967296*
Math.random())};k.on("mousemove scroll click keydown",l);p.on("change","input",l)});$(function(){window.applicationCache&&$("html").attr("manifest")&&$("<aside>",{id:"offline"}).append($("<p>").append($("<img>",{src:"images/offline.png",alt:"This website supports offline mode.",title:"This website supports offline mode.\nIn modern browsers you can use this website without an internet connection.",click:function(){alert("This website supports offline mode.\nIn modern browsers you can use this website without an internet connection.")}}))).appendTo("footer")});
$(function(){function l(f){var k=document.createElement("script");k.src=f;f=document.getElementsByTagName("script")[0];f.parentNode.insertBefore(k,f)}$("#share-text").after('<div id="share-links" hidden><div><ul><li><div class="social-button g-plusone disabled" data-size="medium" data-href="http://baseconvert.com/"></div></li><li><div class="social-button fb-like disabled" data-href="http://baseconvert.com/" data-width="90" data-layout="button_count" data-show-faces="false" data-send="false"></div><div id="fb-root"></div></li></ul></div>');
$(".fb-like").one("click",function(){$(this).removeClass("disabled");l("//connect.facebook.net/en_US/all.js#xfbml=1")});$(".g-plusone").one("click",function(){$(this).removeClass("disabled");l("https://apis.google.com/js/plusone.js")});(function(f){var k,g=$("#share-links");$("body").on("mouseenter",f,function(){clearTimeout(k);g.css("display","inline")});$("body").on("mouseleave",f,function(){k=setTimeout(function(){g.css("display","none")},500)})})("#share-text, #share-links,.gc-bubbleDefault, .pls-container")});